### PR TITLE
Started writing a genome assembly tutorial

### PR DESCRIPTION
**Pull request by bstaats**
Hi folks,

Started documenting a draft genome assembly tutorial. Making this PR to shed some visibility into my progress not necessarily expecting this to get merged until its more complete.

### CODE REVIEW

**Comment by kern3020** [comment]
I can't approve this. But looks fine. I like the --split-files  argument to keep read1 and read2 separate. 

I ran into a problem because sratools cache files in ~/ncbi. Found out you can move it with 
```
# move cache from ~/ to /data/
~/src/sratoolkit.2.8.2-1-ubuntu64/bin/vdb-config -i
```

**Comment by ArturKlauser** [comment]
Same here, I don't have a "merge" option in the UI for this pull request. Brian, can you double check how you sent it?

**Comment by bstaats** [comment]
Added more to the tutorial. In regards to you folks not being able to merge. I'm not able to add any reviewers to the PR thus why you are not able to merge. I keep getting a "You can't perform that action at this time" error.

**Comment by kern3020** [comment]
Installation of these tools can be a pain. I recently started using bioconda (https://bioconda.github.io/). It is smooth. 

With respect to not being able to merge. The error says "those with write access". Do Artur and I have write access?

**Pull request merged**
